name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Mondays at 06:00 UTC

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--config .github/lychee.toml './**/*.md'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
